{{- if .Values.serviceAccount.create -}}
{{- $rand := randAlphaNum 5 -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "app.serviceAccountName" . }}-{{ $rand }}
rules:
  - apiGroups: [ "", "apps", "autoscaling" ]
    resources: [ "horizontalpodautoscalers", "namespaces", "secrets", "services", "deployments", "serviceaccounts", "replicasets", "pods" ]
    verbs: [ "create", "list", "get", "update", "patch", "delete", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.serviceAccountName" . }}-{{ $rand }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.serviceAccountName" . }}-{{ $rand }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
